default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
    <<: *default
    host: localhost
    port: 5432
    username: postgres
    password: postgres

remote: &remote
    <<: *default
    host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
    port: <%= ENV.fetch('DB_PORT') { 5432 } %>
    username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
    password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>

development:
    <<: *local
    database: laser_development

test:
    <<: *local
#    database: laser_test

production:
    <<: *remote
    database: laser_production
